# Detailed explanation of all options available at https://github.com/NEZNAMY/TAB/wiki/config.yml

change-nametag-prefix-suffix: true
change-tablist-prefix-suffix: true
enable-header-footer: true
nametag-refresh-interval-milliseconds: 1000
tablist-refresh-interval-milliseconds: 1000
header-footer-refresh-interval-milliseconds: 100
header:
- ''
- '&a&lGr&2&low'
- ''
footer:
- ''
- '&e%ping%ms &7- &a%tps% &7TPS'
- '&7&o(( &f&n%online%&r &7&ocurrently connected. ))'
- ''
tablist-objective: NONE
tablist-objective-custom-value: '%some_placeholderapi_placeholder%'
group-sorting-priority-list:
- owner
- developer
- admin
- mod
- helper
- builder
- veteran
- farmer
- agriculturist
- tiller
- rookie
- default
Groups:
  Owner:
    tabprefix: '&7[&4Owner&7] &4'
    tagprefix: '&4'
    tabsuffix: '%skript_player::tag_color::{uuid}%%skript_player::tag::{uuid}%'
    tagsuffix: '%skript_player::tag_color::{uuid}%%skript_player::tag::{uuid}%'
  Developer:
    tabprefix: '&7[&bDeveloper&7] &b'
    tagprefix: '&b'
    tabsuffix: '%skript_player::tag_color::{uuid}%%skript_player::tag::{uuid}%'
    tagsuffix: '%skript_player::tag_color::{uuid}%%skript_player::tag::{uuid}%'    
  Admin:
    tabprefix: '&7[&cAdmin&7] &c'
    tagprefix: '&c'
    tabsuffix: '%skript_player::tag_color::{uuid}%%skript_player::tag::{uuid}%'
    tagsuffix: '%skript_player::tag_color::{uuid}%%skript_player::tag::{uuid}%'
  Mod:
    tabprefix: '&7[&3Mod&7] &3'
    tagprefix: '&3'
    tabsuffix: '%skript_player::tag_color::{uuid}%%skript_player::tag::{uuid}%'
    tagsuffix: '%skript_player::tag_color::{uuid}%%skript_player::tag::{uuid}%'    
  Helper:
    tabprefix: '&7[&dHelper&7] &d'
    tagprefix: '&d'
    tabsuffix: '%skript_player::tag_color::{uuid}%%skript_player::tag::{uuid}%'
    tagsuffix: '%skript_player::tag_color::{uuid}%%skript_player::tag::{uuid}%'    
  Veteran:
    tabprefix: '&7[&6Veteran&7] &6'
    tagprefix: '&6'
    tabsuffix: '%skript_player::tag_color::{uuid}%%skript_player::tag::{uuid}%'
    tagsuffix: '%skript_player::tag_color::{uuid}%%skript_player::tag::{uuid}%'    
  Farmer:
    tabprefix: '&7[&eFarmer&7] &e'
    tagprefix: '&e'
    tabsuffix: '%skript_player::tag_color::{uuid}%%skript_player::tag::{uuid}%'
    tagsuffix: '%skript_player::tag_color::{uuid}%%skript_player::tag::{uuid}%'    
  Agriculturist:
    tabprefix: '&7[&cAgriculturist&7] &c'
    tagprefix: '&c'
    tabsuffix: '%skript_player::tag_color::{uuid}%%skript_player::tag::{uuid}%'
    tagsuffix: '%skript_player::tag_color::{uuid}%%skript_player::tag::{uuid}%'    
  Tiller:
    tabprefix: '&7[&2Tiller&7] &2'
    tagprefix: '&2'
    tabsuffix: '%skript_player::tag_color::{uuid}%%skript_player::tag::{uuid}%'
    tagsuffix: '%skript_player::tag_color::{uuid}%%skript_player::tag::{uuid}%'    
  Rookie:
    tabprefix: '&7[&aRookie&7] &a'
    tagprefix: '&a'
    tabsuffix: '%skript_player::tag_color::{uuid}%%skript_player::tag::{uuid}%'
    tagsuffix: '%skript_player::tag_color::{uuid}%%skript_player::tag::{uuid}%'    
  default:
    tabprefix: '&7[&7Newbie&7] &7'
    tagprefix: '&7'
    tabsuffix: '%skript_player::tag_color::{uuid}%%skript_player::tag::{uuid}%'
    tagsuffix: '%skript_player::tag_color::{uuid}%%skript_player::tag::{uuid}%'    
  hfexample:
    header:
    - This is an example for per-group header/footer
    footer:
    - applied to a group
  _OTHER_:
    tabprefix: '%vault-prefix% '
    tagprefix: '%vault-prefix% '
    tabsuffix: ''
    tagsuffix: ''
    customtabname: '%essentialsnick%'
    customtagname: '%essentialsnick%'
Users:
  _uwu:
    tabprefix: '&buwu &f'
    tagprefix: '&3test &f'
    abovename: '&eGaming'
    belowname: '&aGamer'
  MagicPotatoooo: {}
belowname:
  enabled: false
  refresh-interval-milliseconds: 200
  number: '%vault_eco_balance%'
  text: '&bCredits'
enable-collision: true
revert-collision-rule-in-worlds:
- revertedworld
do-not-move-spectators: false
unlimited-nametag-prefix-suffix-mode:
  enabled: false
  modify-npc-names: false
per-world-settings:
  world1:
    header:
    - an example of world with custom
    footer:
    - header/footer and prefix/suffix
    Groups:
      Owner:
        tabprefix: '&0&l[&a&lOwner&0&l] &a'
        tagprefix: '&2&lOwner &a'
  world2-world3:
    header:
    - This is a shared header for
    - world2 and world3
placeholders:
  afk-yes: ''
  afk-no: ''
  date-format: dd.MM.yyyy
  time-format: '[HH:mm:ss / h:mm a]'
  time-offset: 0
  remove-strings:
  - '[]'
  - < >
rank-aliases:
  Admin: '&4&lADMIN'
  Mod: '&b&lMOD'
  Premium: '&6&lPREMIUM'
  Ultra: '&b&lULTRA'
  Legend: '&a&lLEGEND'
  Titan: '&c&lTITAN'
  Youtuber: '&c&lYOUTUBE'
  _OTHER_: '&7No Rank'
disable-features-in-worlds:
  header-footer:
  - disabledworld
  tablist-names:
  - disabledworld
  nametag:
  - disabledworld
  tablist-objective:
  - disabledworld
  bossbar:
  - disabledworld
  belowname:
  - disabledworld