# =---------------= [ Grow ] =---------------=
# This script is part of the Grow Project.
# Originally made by:
# - Jeroeno_Boy
# - DebitCardz
# - Supercrafter100
# - PsekA_F
# PLEASE DO NOT CLAIM THIS SCRIPT AS YOURS
# NOR REMOVE CREDITS FROM THE ORIGINAL
# AUTHOURS.
# ALLOWED:
# - You are allowed to edit the script.
# - You are allowed to use the script for
#   production and/or commercial uses.
# YOU ARE NOT ALLOWED TO:
# - Share an edited version of the script
# - Remove this license text
# - Use without giving credits to the
#   original authors.
# =---------------= [ Grow ] =---------------=


on load:
	delete {-spawners::*}

	wait 1 tick
	set {-head::pig} to player head with nbt "{display:{Name:""pig""},SkullOwner:{Id:""e1e1c2e4-1ed2-473d-bde2-3ec718535399"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjIxNjY4ZWY3Y2I3OWRkOWMyMmNlM2QxZjNmNGNiNmUyNTU5ODkzYjZkZjRhNDY5NTE0ZTY2N2MxNmFhNCJ9fX0=""}]}}}"
	set {-head::chicken} to player head with nbt "{display:{Name:""chicken""},SkullOwner:{Id:""7d3a8ace-e045-4eba-ab71-71dbf525daf1"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTYzODQ2OWE1OTljZWVmNzIwNzUzNzYwMzI0OGE5YWIxMWZmNTkxZmQzNzhiZWE0NzM1YjM0NmE3ZmFlODkzIn19fQ==""}]}}}"
	set {-head::cow} to player head with nbt "{display:{Name:""cow""},SkullOwner:{Id:""97ddf3b3-9dbe-4a3b-8a0f-1b19ddeac0bd"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWQ2YzZlZGE5NDJmN2Y1ZjcxYzMxNjFjNzMwNmY0YWVkMzA3ZDgyODk1ZjlkMmIwN2FiNDUyNTcxOGVkYzUifX19""}]}}}"
	set {-head::sheep} to player head with nbt "{display:{Name:""sheep""},SkullOwner:{Id:""fa234925-9dbe-4b8f-a544-7c70fb6b6ac5"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjMxZjljY2M2YjNlMzJlY2YxM2I4YTExYWMyOWNkMzNkMThjOTVmYzczZGI4YTY2YzVkNjU3Y2NiOGJlNzAifX19""}]}}}"
	set {-head::zombie} to player head with nbt "{display:{Name:""zombie""},SkullOwner:{Id:""9959dd98-efb3-4ee9-a8fb-2fda0218cda0"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTZmYzg1NGJiODRjZjRiNzY5NzI5Nzk3M2UwMmI3OWJjMTA2OTg0NjBiNTFhNjM5YzYwZTVlNDE3NzM0ZTExIn19fQ==""}]}}}"
	set {-head::skeleton} to player head with nbt "{display:{Name:""skeleton""},SkullOwner:{Id:""99653361-7f17-4868-af3b-c95bc2743f5e"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzAxMjY4ZTljNDkyZGExZjBkODgyNzFjYjQ5MmE0YjMwMjM5NWY1MTVhN2JiZjc3ZjRhMjBiOTVmYzAyZWIyIn19fQ==""}]}}}"
	set {-head::spider} to player head with nbt "{display:{Name:""spider""},SkullOwner:{Id:""8bdb71d0-4724-48b2-9344-e79480424798"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2Q1NDE1NDFkYWFmZjUwODk2Y2QyNThiZGJkZDRjZjgwYzNiYTgxNjczNTcyNjA3OGJmZTM5MzkyN2U1N2YxIn19fQ==""}]}}}"
	set {-head::creeper} to player head with nbt "{display:{Name:""creeper""},SkullOwner:{Id:""eed2d903-ca32-4cc7-b33b-ca3bdbe18da4"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjQyNTQ4MzhjMzNlYTIyN2ZmY2EyMjNkZGRhYWJmZTBiMDIxNWY3MGRhNjQ5ZTk0NDQ3N2Y0NDM3MGNhNjk1MiJ9fX0=""}]}}}"
	set {-head::slime} to player head with nbt "{display:{Name:""slime""},SkullOwner:{Id:""8321287f-584b-4e81-82c1-692bcd63ccc8"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTIwZTg0ZDMyZDFlOWM5MTlkM2ZkYmI1M2YyYjM3YmEyNzRjMTIxYzU3YjI4MTBlNWE0NzJmNDBkYWNmMDA0ZiJ9fX0=""}]}}}"
	set {-head::blaze} to player head with nbt "{display:{Name:""blaze""},SkullOwner:{Id:""7ceb88b2-7f5f-4399-abb9-7068251baa9d"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjc4ZWYyZTRjZjJjNDFhMmQxNGJmZGU5Y2FmZjEwMjE5ZjViMWJmNWIzNWE0OWViNTFjNjQ2Nzg4MmNiNWYwIn19fQ==""}]}}}"
	set {-head::pigman} to player head with nbt "{display:{Name:""pigman""},SkullOwner:{Id:""6540c046-d6ea-4aff-9766-32a54ebe6958"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzRlOWM2ZTk4NTgyZmZkOGZmOGZlYjMzMjJjZDE4NDljNDNmYjE2YjE1OGFiYjExY2E3YjQyZWRhNzc0M2ViIn19fQ==""}]}}}"
	set {-head::witch} to player head with nbt "{display:{Name:""witch""},SkullOwner:{Id:""7f92b3d6-5ee0-4ab6-afae-2206b9514a63"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjBlMTNkMTg0NzRmYzk0ZWQ1NWFlYjcwNjk1NjZlNDY4N2Q3NzNkYWMxNmY0YzNmODcyMmZjOTViZjlmMmRmYSJ9fX0=""}]}}}"
	set {-head::guardian} to player head with nbt "{display:{Name:""guardian""},SkullOwner:{Id:""628f15d0-e39c-4fd9-9c4e-8c41d4f54b29"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTBiZjM0YTcxZTc3MTViNmJhNTJkNWRkMWJhZTVjYjg1Zjc3M2RjOWIwZDQ1N2I0YmZjNWY5ZGQzY2M3Yzk0In19fQ==""}]}}}"
	set {-head::ironGolem} to player head with nbt "{display:{Name:""irongolem""},SkullOwner:{Id:""cd7a3275-c3b4-4cf7-85e2-6419ffdc449a"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjJiY2FjZWViNDE2MmY0MDBkNDQ3NDMzMTU5MzJhYzgyMGQzMTE5YWM4OTg2YTAxNjFhNzI2MTYxY2NjOTNmYyJ9fX0=""}]}}}"
	set {-head::villager} to player head with nbt "{display:{Name:""villager""},SkullOwner:{Id:""0a9e8efb-9191-4c81-80f5-e27ca5433156"",Properties:{textures:[{Value:""eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODIyZDhlNzUxYzhmMmZkNGM4OTQyYzQ0YmRiMmY1Y2E0ZDhhZThlNTc1ZWQzZWIzNGMxOGE4NmU5M2IifX19""}]}}}"

	spawner_add({-head::pig}, "pig", 65000)
	spawner_add({-head::chicken}, "chicken", 75000)
	spawner_add({-head::cow}, "cow", 85000)
	spawner_add({-head::sheep}, "sheep", 85000)
	spawner_add({-head::zombie}, "zombie", 125000)
	spawner_add({-head::skeleton}, "skeleton", 175000)
	spawner_add({-head::spider}, "spider", 225000)
	spawner_add({-head::creeper}, "creeper", 325000)
	spawner_add({-head::slime}, "slime", 425000)
	spawner_add({-head::blaze}, "blaze", 625000)
	spawner_add({-head::pigman}, "pig_zombie", 750000)
	spawner_add({-head::witch}, "witch", 1250000)
	spawner_add({-head::guardian}, "guardian", 1750000)
	spawner_add({-head::irongolem}, "iron_golem", 2850000)
	spawner_add({-head::villager}, "villager", 5000000)


function openSpawners(p: player):
	#shop_loadCat({_cat}, {_p})

	open virtual chest inventory with size 6 named "&8Shop > Spawners" to {_P}
	fillinventory({_P})

	play sound "ui.button.click" with volume 0.5 at {_P} for {_P}
	format gui slot 40 of {_P} with 1 barrier named "&c&lGo Back" with lore "&8&m                        ||&7Click to go to||&7the main menu||&8&m                        " to run:
		play sound "ui.button.click" with volume 0.5 at {_P} for {_P}
		openShop({_P})

	set {_multiplier} to 0
	set {_add} to 9
	set {_i} to 0
	loop {-spawners::list::*}:
		add 1 to {_i}
		if {_i} > {_multiplier}:
			if {_i} < {_multiplier} + 22:
				add 1 to {_add}
				if {_add} = 17 or 26:
					add 2 to {_add}

				set {_item} to {-spawners::spawner::%loop-value%::display}
				set {_name} to ReitemName(loop-value)
				set {_price} to {-spawners::spawner::%loop-value%::price}

				set {_lore} to "&8&m                        ||&7Click to buy||&8> &fBuy: &e$%easyRead(buy({_price}))%||&8&m                        "

				format gui slot {_add} of {_P} with {_item} named "&e&l%{_name}% &fSpawner" with lore {_lore} to run function spawner_checkbuyorsomething({_P}, loop-value)
			else:
				stop


function spawner_checkbuyorsomething(p: player, name: string, amount: number = 0):

	if {_amount} <= 1:
		open virtual chest inventory with size 6 named "&8Shop > Spawners > %ReitemName({_name})%" to {_P}
		fillinventory({_P})
		set {_amount} to 1

		
	play sound "ui.button.click" with volume 0.5 at {_P} for {_P}
	format gui slot 40 of {_P} with 1 barrier named "&c&lGo Back" with lore "&8&m                        ||&7Click to go to||&7the main menu||&8&m                        " to run:
		play sound "ui.button.click" with volume 0.5 at {_P} for {_P}
		openSpawners({_P})

	set {_price} to buy({-spawners::spawner::%{_name}%::price}*{_amount})
	set {_lore} to "&8&m                        ||&7Click to buy||&8> &fBuy: &e$%easyRead(buy({-spawners::spawner::%{_name}%::price}))%||&8&m                        "
	set {_item} to {-spawners::spawner::%{_name}%::display}
	format gui slot 13 of {_P} with {_item} named "&e&l%{_name}% &fSpawner" with lore {_lore}
	format gui slot 22 of {_p} with 1 emerald named "&a&lClick to buy" with lore "&8&m                        ||&7Click to buy %ReitemName({_name})%||||&7> &fAmount: &a%easyRead({_amount})%||&8> &fPrice: &e$%easyRead({_price})%||&8&m                        " to run function spawner_buy({_name}, {_p}, {_price}, {_amount})
	
	spawner_format(red stained glass pane, {_p}, {_name}, {_amount}, 11, -100)
	spawner_format(orange stained glass pane, {_p}, {_name}, {_amount}, 19, -10)
	spawner_format(yellow stained glass pane, {_p}, {_name}, {_amount}, 29, -1)

	spawner_format(blue stained glass pane, {_p}, {_name}, {_amount}, 15, 100)
	spawner_format(cyan stained glass pane, {_p}, {_name}, {_amount}, 25, 10)
	spawner_format(light blue stained glass pane, {_p}, {_name}, {_amount}, 33, 1)


function spawner_add(display: item, name: string, price: number):
	add {_name} to {-spawners::list::*}
	set {-spawners::spawner::%{_name}%::display} to {_display}
	set {-spawners::spawner::%{_name}%::price} to {_price}


function spawner_buy(spawner: string, p: player, price: number, amount: number):
	set {_uuid} to {_p}'s uuid
	if {_P}'s inventory can hold 1 barrier:
		if {_P}'s balance >= {_price}:

			log "(LOG):SPAWNER_BUY:%{_uuid}%:%{_id}%:%{_amount}%:%{_amount}*{ShopItem::item::%{_id}%::sell}%" to "transactions.log"
			log "(MSG):%{_P}% bought (SPAWNER_BUY) %{_amount}% of %{_id}% for %{_amount}*{ShopItem::item::%{_id}%::sell}%" to "transactions.log"
			
			play sound "block.note.harp" with volume 1 at {_P} for {_P}
			execute console command "stacker give -s %{_p}% spawner %{_spawner}% %{_amount}%"
			message "&2(&a&l*&2) &7You bought &e%{_amount}% %ReitemName({_spawner})% &fspawners" to {_P}
			remove {_price} from {_P}'s balance
			openSpawners({_p})
		else:
			play sound "entity.villager.hurt" with volume 1 at {_P} for {_P}
			send "&4(&c&l*&4) &7You need &e$%easyRead({_price})% &7to purchase this item." to {_P} # <-- Congrats you learned proper grammar! - Your proud father DebitCardz.
	else:
		play sound "entity.villager.hurt" with volume 1 at {_P} for {_P}
		message "&4(&c&l*&4) &7Your inventory is too full!" to {_P}


function spawner_format(item: item, p: player, id: string, amount: number, slot: number, adder: number):
	if {_adder} < 0:
		set {_t} to "&c%{_adder}*-1%"
	else:
		set {_t} to "&a%{_adder}%"
	set {_price} to {-spawners::spawner::%{_id}%::price}
	format gui slot {_slot} of {_p} with 1 of {_item} named "&7%{_adder} > 0 ? ""Add"" : ""Remove""% %{_t}%" with lore "&8&m                        ||&7click to %{_adder} > 0 ? ""add"" : ""remove""% %{_t}%||||&8> &fAmount: &a%easyRead({_amount})% &e(%{_adder} > 0 ? ""+"" : """"%%{_adder}%)||&8> &fCurrent Price: &e$%easyRead(buy({_price}*{_amount}))%||&8&m                        " to run function spawner_checkbuyorsomething({_P}, {_id}, {_amount}+{_adder})